version: "3"
services:
  living_wage_bot:
    build:
      context: .
      dockerfile: Dockerfile
      
    image: living-wage-bot
    network_mode: host

    environment:
      - "JAVA_OPTS="
      - spring.profiles.active=prod

    restart: always
